// <auto-generated />
using System;
using Finance.Infrastructure.Persistance.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Finance.Infrastructure.Persistance.Migrations
{
    [DbContext(typeof(FinanceDbContext))]
    [Migration("20230917152857_new seed data")]
    partial class newseeddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Finance.Domain.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int?>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<int?>("ConstructionSiteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("MachineryId")
                        .HasColumnType("integer");

                    b.Property<int?>("MaintenanceRecordId")
                        .HasColumnType("integer");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ReferenceId")
                        .HasColumnType("integer");

                    b.Property<int?>("ToolId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Expense");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1059.12m,
                            ConstructionSiteId = 1,
                            Date = new DateTime(2023, 9, 17, 15, 28, 57, 39, DateTimeKind.Utc).AddTicks(3710),
                            Description = "Mostar Olymic pool expenses",
                            ReferenceId = 1112
                        },
                        new
                        {
                            Id = 2,
                            Amount = 87.8m,
                            Date = new DateTime(2023, 9, 17, 15, 28, 57, 39, DateTimeKind.Utc).AddTicks(3716),
                            Description = "Tool purchase",
                            ReferenceId = 132,
                            ToolId = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 188.07m,
                            Date = new DateTime(2023, 9, 17, 15, 28, 57, 39, DateTimeKind.Utc).AddTicks(3719),
                            Description = "Circular saw service",
                            MaintenanceRecordId = 4,
                            ReferenceId = 132
                        });
                });

            modelBuilder.Entity("Finance.Domain.Entities.ExpenseItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExpenseId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseId");

                    b.ToTable("ExpenseItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 112m,
                            Description = "Fuel for Komatsu PC200 excavator",
                            ExpenseId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 212.8m,
                            Description = "Fuel for Caterpillar 320d excavator",
                            ExpenseId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 723.2m,
                            Description = "Food",
                            ExpenseId = 1
                        },
                        new
                        {
                            Id = 4,
                            Amount = 10.5m,
                            Description = "Hydraulic fluid for Komatsu PC200 excavator",
                            ExpenseId = 1
                        },
                        new
                        {
                            Id = 5,
                            Amount = 11.12m,
                            Description = "Renting dump truck",
                            ExpenseId = 1
                        },
                        new
                        {
                            Id = 6,
                            Amount = 87.8m,
                            Description = "Mallet purchase",
                            ExpenseId = 2
                        },
                        new
                        {
                            Id = 7,
                            Amount = 87.15m,
                            Description = "Circular Saw",
                            ExpenseId = 3
                        },
                        new
                        {
                            Id = 8,
                            Amount = 100.92m,
                            Description = "Oil",
                            ExpenseId = 3
                        });
                });

            modelBuilder.Entity("Finance.Domain.Entities.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("ArticleId")
                        .HasColumnType("integer");

                    b.Property<int>("ConstructionSiteId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MachineryId")
                        .HasColumnType("integer");

                    b.Property<int>("MaintenanceRecordId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("ToolId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Invoice");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1298.92m,
                            ArticleId = 0,
                            ConstructionSiteId = 0,
                            Date = new DateTime(2023, 9, 17, 15, 28, 57, 39, DateTimeKind.Utc).AddTicks(3564),
                            DueDate = new DateTime(2023, 9, 17, 15, 28, 57, 39, DateTimeKind.Utc).AddTicks(3568),
                            MachineryId = 0,
                            MaintenanceRecordId = 0,
                            OrderId = 1,
                            ToolId = 0
                        });
                });

            modelBuilder.Entity("Finance.Domain.Entities.InvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("InvoiceItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 500m,
                            Description = "Cement",
                            InvoiceId = 1
                        },
                        new
                        {
                            Id = 2,
                            Amount = 350m,
                            Description = "Parquet floor",
                            InvoiceId = 1
                        },
                        new
                        {
                            Id = 3,
                            Amount = 448.92m,
                            Description = "Bricks",
                            InvoiceId = 1
                        });
                });

            modelBuilder.Entity("Finance.Domain.Entities.ExpenseItem", b =>
                {
                    b.HasOne("Finance.Domain.Entities.Expense", null)
                        .WithMany("Items")
                        .HasForeignKey("ExpenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Finance.Domain.Entities.InvoiceItem", b =>
                {
                    b.HasOne("Finance.Domain.Entities.Invoice", null)
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Finance.Domain.Entities.Expense", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Finance.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
