// <auto-generated />
using System;
using Equipment.Infrastructure.Persistance.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Equipment.Infrastructure.Persistance.Migrations
{
    [DbContext(typeof(EquipmentDbContext))]
    [Migration("20230917152805_new seed data")]
    partial class newseeddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Equipment.Domain.Entities.Machinery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConstructionSiteId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("retired")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Machinery");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConstructionSiteId = 1,
                            Description = "SN: KPC200",
                            Location = "Mostar Construction Site",
                            Name = "Komatsu PC200 excavator",
                            retired = false
                        },
                        new
                        {
                            Id = 2,
                            ConstructionSiteId = 2,
                            Description = "SN: C320d",
                            Location = "Sarajevo",
                            Name = "Caterpillar 320d excavator",
                            retired = false
                        },
                        new
                        {
                            Id = 3,
                            ConstructionSiteId = 2,
                            Description = "SN: VEC210D",
                            Location = "Sarajevo",
                            Name = "Volvo EC210D excavator",
                            retired = false
                        },
                        new
                        {
                            Id = 4,
                            ConstructionSiteId = 2,
                            Description = "SN: L132hc",
                            Location = "Sarajevo",
                            Name = "Liebherr 132 hc tower crane",
                            retired = false
                        },
                        new
                        {
                            Id = 5,
                            ConstructionSiteId = 1,
                            Description = "SN: SSP1800",
                            Location = "Mostar",
                            Name = "Schwing concrete pump",
                            retired = false
                        },
                        new
                        {
                            Id = 6,
                            ConstructionSiteId = 3,
                            Description = "SN: CAP300",
                            Location = "Konjic",
                            Name = "Caterpillar asphalt paver",
                            retired = false
                        },
                        new
                        {
                            Id = 7,
                            ConstructionSiteId = 3,
                            Description = "SN: C797",
                            Location = "Konjic",
                            Name = "Caterpillar dump truck",
                            retired = false
                        },
                        new
                        {
                            Id = 8,
                            ConstructionSiteId = 3,
                            Description = "SN: BAC200",
                            Location = "Konjic",
                            Name = "BOMAG roller compactor",
                            retired = false
                        },
                        new
                        {
                            Id = 9,
                            ConstructionSiteId = 3,
                            Description = "SN: MTGS",
                            Location = "Konjic",
                            Name = "MAN concrete roller truck",
                            retired = false
                        },
                        new
                        {
                            Id = 10,
                            ConstructionSiteId = 3,
                            Description = "SN: Kd65",
                            Location = "Konjic",
                            Name = "Komatsu bulldozer",
                            retired = false
                        });
                });

            modelBuilder.Entity("Equipment.Domain.Entities.Tool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConstructionSiteId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("retired")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Tool");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConstructionSiteId = 1,
                            Description = "",
                            Location = "Mostar",
                            Title = "Hammer",
                            retired = false
                        },
                        new
                        {
                            Id = 2,
                            ConstructionSiteId = 1,
                            Description = "",
                            Location = "Mostar",
                            Title = "Level",
                            retired = false
                        },
                        new
                        {
                            Id = 3,
                            ConstructionSiteId = 1,
                            Description = "",
                            Location = "Mostar",
                            Title = "Chisel",
                            retired = false
                        },
                        new
                        {
                            Id = 4,
                            ConstructionSiteId = 1,
                            Description = "",
                            Location = "Mostar",
                            Title = "Mallet",
                            retired = false
                        },
                        new
                        {
                            Id = 5,
                            ConstructionSiteId = 1,
                            Description = "Phillips",
                            Location = "Mostar",
                            Title = "Screwdriver Set",
                            retired = false
                        },
                        new
                        {
                            Id = 6,
                            ConstructionSiteId = 1,
                            Description = "",
                            Location = "Mostar",
                            Title = "Cordless Dril",
                            retired = false
                        },
                        new
                        {
                            Id = 7,
                            ConstructionSiteId = 2,
                            Description = "",
                            Location = "Sarajevo",
                            Title = "Jigsaw",
                            retired = false
                        },
                        new
                        {
                            Id = 8,
                            ConstructionSiteId = 2,
                            Description = "",
                            Location = "Sarajevo",
                            Title = "Heat Gun",
                            retired = false
                        },
                        new
                        {
                            Id = 9,
                            ConstructionSiteId = 2,
                            Description = "",
                            Location = "Sarajevo",
                            Title = "Table Saw",
                            retired = false
                        },
                        new
                        {
                            Id = 10,
                            ConstructionSiteId = 2,
                            Description = "",
                            Location = "Sarajevo",
                            Title = "Belt sander",
                            retired = false
                        },
                        new
                        {
                            Id = 11,
                            ConstructionSiteId = 2,
                            Description = "",
                            Location = "Sarajevo",
                            Title = "Router",
                            retired = false
                        },
                        new
                        {
                            Id = 12,
                            ConstructionSiteId = 2,
                            Description = "",
                            Location = "Sarajevo",
                            Title = "Hammer",
                            retired = false
                        },
                        new
                        {
                            Id = 13,
                            ConstructionSiteId = 3,
                            Description = "",
                            Location = "Konjic",
                            Title = "Utility Bar",
                            retired = false
                        },
                        new
                        {
                            Id = 14,
                            ConstructionSiteId = 3,
                            Description = "Flat",
                            Location = "Konjic",
                            Title = "Screwdriver set",
                            retired = false
                        },
                        new
                        {
                            Id = 15,
                            ConstructionSiteId = 3,
                            Description = "",
                            Location = "Konjic",
                            Title = "Circular Saw",
                            retired = false
                        },
                        new
                        {
                            Id = 16,
                            ConstructionSiteId = 3,
                            Description = "",
                            Location = "Konjic",
                            Title = "Nail Gun",
                            retired = false
                        },
                        new
                        {
                            Id = 17,
                            ConstructionSiteId = 3,
                            Description = "",
                            Location = "Konjic",
                            Title = "Chalk Line",
                            retired = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
